language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-7
      - clang-3.6
script:
  - cmake -H./formatter_lib -B./formatter_lib/build
  - cmake -H./formatter_ex_lib -B./formatter_ex_lib/build
  - cmake -H./hello_world_application -B./hello_world_application/build
  - cmake -H./solver_application -B./solver_application/build

